# Generated by Django 3.1.1 on 2021-03-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210324_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='regularuser',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
