# Generated by Django 3.1.1 on 2021-03-23 07:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210321_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('event_type', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('start_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_approved', models.BooleanField(default=False)),
                ('upvotes_count', models.IntegerField(default=0)),
                ('street', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('province', models.CharField(blank=True, default='', max_length=128, null=True)),
            ],
            options={
                'db_table': 'Event',
            },
        ),
        migrations.AddField(
            model_name='regularuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='regularuser',
            name='is_organizer',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('user_type', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='app.event')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senders', to='app.regularuser')),
            ],
            options={
                'db_table': 'Request',
            },
        ),
    ]
