# Generated by Django 3.1.1 on 2021-03-24 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to='app.organizeruser'),
        ),
        migrations.AlterField(
            model_name='administratoruser',
            name='regular_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrator', to='app.regularuser'),
        ),
        migrations.AlterField(
            model_name='organizeruser',
            name='regular_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to='app.regularuser'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='app.regularuser'),
        ),
    ]
