# Generated by Django 3.1.7 on 2021-03-25 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210324_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='request',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(to='app.RegularUser'),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='event_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='app.event'),
        ),
    ]
